[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "Amc5TwKoUEoFyZQhAsnAWRKe9EA9wBfkgeTMnV2ufPFU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kash/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
